version: '2.1'

services:
  pastgresql:
    image: postgres:11
    container_name: "postgres"
    hostname: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "orders_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5